# Numpy Installation

In [1]:
!pip install numpy

You should consider upgrading via the 'c:\python37\python.exe -m pip install --upgrade pip' command.


# Checking numpy installation by importing numpy and with alias name

In [2]:
import numpy as np

# Checking numpy version

In [3]:
print(np.__version__)

1.18.1


# Creating first numpy array

In [4]:
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


# Checking type of array created

In [5]:
print(type(arr))

<class 'numpy.ndarray'>


# Using tuple to create numpy array (We can use any array like object)

In [6]:
arr2=np.array((6,7,8,9,10))
print(arr2,type(arr2),sep="\n")

[ 6  7  8  9 10]
<class 'numpy.ndarray'>


# Creating OD array and checking its dimensions

In [7]:
arr0=np.array(42)
print(arr0,arr0.ndim,sep="\n")

42
0


# Creating 1D array and checking its dimensions

In [8]:
arr1=np.array([5,6,7,8])
print(arr1,arr1.ndim,sep="\n")

[5 6 7 8]
1


# Creating 2D array / Matrix / 2D Tensor and checking its dimensions

In [9]:
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2,arr2.ndim,sep="\n")

[[1 2 3]
 [4 5 6]]
2


# Creating 3D array/ 3D Tensor and checking its dimensions

In [10]:
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3,arr3.ndim,sep="\n")

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3


# Creating n dimensional array using ndmin argument

In [11]:
arrn=np.array([1,2,3,4],ndmin=5)
print(arrn,arrn.ndim,sep="\n")

[[[[[1 2 3 4]]]]]
5


# Accessing 1D array elements

In [12]:
arr1=np.array([1,2,3,4])
print(arr[0])  #First element
print(arr[1])
print(arr[4])  #Last element
print(arr[-1]) #Last element
print(arr[0]+arr[2])

1
2
5
5
4


# Accessing 2D array elements

In [13]:
arr2=np.array([[1,2,3,4],[5,6,7,8]])
print("Second element of first list =",arr2[0,1])
print("Last element of second list =",arr2[1,-1])
print("First list",arr2[0])
print("Second list",arr2[1])

Second element of first list = 2
Last element of second list = 8
First list [1 2 3 4]
Second list [5 6 7 8]


# Accessing 3D array elements

In [14]:
arr3=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
print("Accessing first array:",arr3[0],sep="\n")
print("Accessing second array of first array =",arr3[0,1])
print("Fourth element of second array of first array =",arr3[0,1,3])

Accessing first array:
[[1 2 3 4]
 [5 6 7 8]]
Accessing second array of first array = [5 6 7 8]
Fourth element of second array of first array = 8


# Slicing 1D arrays

In [31]:
arr1=np.array([1,2,3,4,5,6])
print("arr1[:3] =",arr1[:3])
print("arr1[3:] =",arr1[3:])
print("arr1[2:4] =",arr1[2:4])
print("arr1[::] =",arr1[::])
print("arr1[::2] =",arr1[::2])
print("arr1[-3:-1] =",arr1[-3:-1])
print("arr1[::-1] =",arr1[::-1])

arr1[:3] = [1 2 3]
arr1[3:] = [4 5 6]
arr1[2:4] = [3 4]
arr1[::] = [1 2 3 4 5 6]
arr1[::2] = [1 3 5]
arr1[-3:-1] = [4 5]
arr1[::-1] = [6 5 4 3 2 1]


# Slicing 2D arrays

In [17]:
arr2=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(arr2[1,1:4])   #From second element, slice index 1 to 4
print(arr2[0:2,2])   #From both elements, slice index 2
print(arr2[0:2,1:4]) #From both elements, slice index 1 to 4

[ 8  9 10]
[3 9]
[[ 2  3  4]
 [ 8  9 10]]


# Checking datatype of an array

In [21]:
arr=np.array([1,2,3,4,5])
print(arr.dtype)

arr2=np.array(["apple","banana","grapes"])
print(arr2.dtype)

int32
<U6


# Defining datatype for array

In [23]:
arr=np.array([1,2,3,4],dtype='S')
print(arr,arr.dtype,sep="\n")

[b'1' b'2' b'3' b'4']
|S1


# Creating array of a datatype with size

In [24]:
arr=np.array([1,2,3,4],dtype='i4')
print(arr,arr.dtype,sep="\n")

[1 2 3 4]
int32


# Copying the array and changing datatype

In [28]:
arr=np.array([1.1,2.1,3.3,4.1])
print(arr,arr.dtype)

arr2=arr.astype('i')
print(arr2,arr2.dtype)

arr3=arr.astype('int')
print(arr3,arr3.dtype)

arr=np.array([1,0,3])
arr4=arr.astype('bool')
print(arr4,arr4.dtype)

[1.1 2.1 3.3 4.1] float64
[1 2 3 4] int32
[1 2 3 4] int32
[ True False  True] bool
